vich_uploader:
    db_driver: orm

    mappings:
        audios:
            uri_prefix: /audios
            upload_destination: '%kernel.project_dir%/public/audios'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        videos:
            uri_prefix: /videos
            upload_destination: '%kernel.project_dir%/public/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        mes_images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer